/*
 * tower_oil_pressure_port.c -- L2 C middle layer for the L0 cell "oil-pressure-port".
 * GENERATED by tools/tower/emith.py from oil-pressure-port.cell.yaml -- do not edit by hand;
 * edit the cell, regenerate, and re-run tools/tower/verify.py.
 * SEMANTIC-TOWER 3: the middle layer is the verification surface, so the
 * entire cell spec is quoted below; each code section quotes the line it
 * implements. A human audits this file against L0 without reading Python.
 *
 * Provenance (ST 4.3): source oil-pressure-port.cell.yaml sha256/16 733981246b917102
 *
 * --------------------------- the cell, quoted verbatim --------------------
 *   name              : oil-pressure-port
 *   description       : Engine oil pressure. A 0.5-4.5 V transducer spanning 0-150 psi,
 *                       read as raw integer millivolts and rendered to whole PSI for the
 *                       game twin.
 *   io[0]             : adc_pin kind=adc unit=V -- transducer output voltage (0.5-4.5 V
 *                       across the 0-150 psi range)
 *   raw.quantity      : transducer millivolts, integer
 *   raw.prefilter     : moving_median window=5
 *   rendering.equation: psi = (mV - 500) * 3 / 80
 *   rendering.basis   : 1/80 psi -- span 4000 mV * 3/80 = 150 psi exactly
 *   rendering.range   : psi in [0, 150]
 *   rendering.quantize: whole_psi (Pythagorean snapping, 1-D)
 *   rendering.deadband: 1 whole psi (unit psi)
 *   snap.twin_endpoint: twin://game/oil-pressure-port/psi
 *   snap.dial         : deadband_psi
 *   tick.period_ms    : 100
 * --------------------------------------------------------------------------
 *
 * Target substrate note (ST 7 table, the rows this family consumes):
 * numeric discipline = integer-only (no FPU assumed, weakest-substrate
 * rule ST 5.3); allocation policy = none-in-loop, flat static state;
 * tick = caller-driven fixed timestep; IO surface = one integer-mV adapter
 * (weak); verification harness = tools/tower/verify.py (host gcc).
 *
 * Contract, one line (ST 5.5): agree-to-within-D, snap-on-exceed,
 * reality-wins, log-both-books, all-integer, fixed-tick. Concretely:
 *   - no floating-point types anywhere in this file, on purpose;
 *   - no allocation inside the tick; state is a flat static image;
 *   - the snap judge compares in squared form (ST 5.2), no square root;
 *   - posts happen only on SNAP, and carry the QUF state line (ST 5.4/6).
 */
#include <stdint.h>
#include <stddef.h>

/* ============================================================== constants =
 * Every constant below is copied from the cell spec quoted in the file
 * header. Nothing numeric is invented here; the compiler only chose
 * representations, which is below the attention horizon (ST 1).
 */
#define TOWER_CELL_NAME       "oil-pressure-port"
#define TOWER_TWIN_ENDPOINT   "twin://game/oil-pressure-port/psi"
#define TOWER_DIAL_DEADBAND   "deadband_psi"
#define TOWER_MED_WINDOW      5   /* raw.prefilter: moving_median */
#define TOWER_EQ_OFFSET_mV    500    /* rendering.equation: psi = (mV - 500) * 3 / 80 */
#define TOWER_EQ_NUM          3      /* numerator of the basis slope */
#define TOWER_EQ_DEN          80      /* rendering.basis: 1/80 psi */
#define TOWER_PSI_MIN         0
#define TOWER_PSI_MAX         150
#define TOWER_DEADBAND_WHOLE  1 /* rendering.deadband.whole (D) */
#define TOWER_TICK_PERIOD_MS  100   /* tick.period_ms (loop config) */
#define TOWER_QUF_LINE_MAX    192

/* ================================================================== state =
 * State-is-a-file: flat static storage, nothing allocated in the loop
 * (ST 5.4: the no-allocation game rule is the QUF doctrine). The whole
 * image is renderable as one QUF-readable line by tower_quf_line(); every
 * stage of the chain is a visible field, which is the maintenance-zoom
 * invariant (ST 6): raw IO -> prefilter -> equation -> whole psi -> twin.
 */
static int32_t  med_win[TOWER_MED_WINDOW]; /* ring of raw mV samples     */
static uint8_t  med_len;                   /* samples held, < window     */
static uint8_t  med_idx;                   /* next ring slot to write    */
static int32_t  st_raw_mV;                 /* latest raw sample          */
static int32_t  st_med_mV;                 /* median of the window       */
static int32_t  st_psi80;                  /* rendered, 1/80 psi          */
static int32_t  st_psi;                    /* whole psi (report lattice) */
static int32_t  st_twin;                   /* what we believe the twin   */
static uint8_t  st_twin_known;             /* 0 until first snap syncs   */
static uint32_t st_posts;                  /* snaps posted to endpoint   */
static int32_t  st_snap_debt;              /* sum of corrections (ST 5.4)*/
static uint32_t st_tick;                   /* qm_tick count              */

/* ========================================================= public surface */
#if defined(__GNUC__)
#define TOWER_WEAK __attribute__((weak))
#else
#define TOWER_WEAK
#endif

TOWER_WEAK int32_t tower_adc_read_mV(void);                 /* glue: raw */
TOWER_WEAK void    tower_twin_post(const char *, const char *); /* glue  */
void     tower_tick(void);                       /* one fixed timestep   */
void     tower_reset(void);                      /* zero the image      */
size_t   tower_quf_line(char *buf, size_t n);    /* QUF state line      */
int32_t  tower_raw_mV(void);
int32_t  tower_med_mV(void);
int32_t  tower_psi80(void);
int32_t  tower_psi_whole(void);
int32_t  tower_twin_psi(void);
uint32_t tower_posts(void);
int32_t  tower_snap_debt(void);
uint32_t tower_ticks(void);
void     tower_twin_set_belief(int32_t v);       /* host/game-side seam */

/* ============================================================== raw IO ====
 * io[0]: adc_pin -- kind adc, unit V (transducer output voltage (0.5-4.5 V across the 0-150 psi range))
 * raw.quantity: transducer millivolts, integer
 * The cell sees ONLY integer millivolts. Counts-to-mV and pin setup are
 * platform concerns, below the horizon; override the weak default in a
 * board file:
 *   Arduino-ESP32 : return analogReadMilliVolts(adc_pin);
 *   ESP-IDF       : adc_oneshot_read + counts * VREF_mV / 4095 (integer)
 */
TOWER_WEAK int32_t tower_adc_read_mV(void)
{
    return 0; /* board glue must override */
}

/* ==================================================== twin transport ======
 * snap.twin_endpoint: twin://game/oil-pressure-port/psi
 * Posting happens ONLY on a SNAP verdict, and the payload is the QUF
 * state line itself -- one line, both books, nonce = the tick count (ST
 * 5.4). Redelivery safety is the ledger's job (idempotence, FOUNDATION
 * D3), not this cell's: the transport never blocks, never retries.
 * Override with a strong definition (UART line, MQTT, HTTP, fabric flit).
 */
TOWER_WEAK void tower_twin_post(const char *endpoint, const char *state_line)
{
    (void)endpoint;
    (void)state_line;
}

/* ============================================================ prefilter ===
 * raw.prefilter: moving_median, window 5
 * Median of the last 5 integer mV samples: an exact integer
 * statistic. Fewer than half the window corrupt keeps the median
 * unchanged -- one ignition spike moves the mean but cannot move this
 * median at all. Sorts a fixed stack copy; no allocation in the loop.
 */
static int32_t median_of(int32_t *a, uint8_t n)
{
    uint8_t i;
    for (i = 1; i < n; i++) {
        int32_t k = a[i];
        int8_t j = (int8_t)(i - 1);
        while (j >= 0 && a[j] > k) {
            a[j + 1] = a[j];
            j--;
        }
        a[j + 1] = k;
    }
    return a[n / 2]; /* window is odd (spec): a real sample, never a mean */
}

static int32_t prefilter_push(int32_t raw_mV)
{
    int32_t win[TOWER_MED_WINDOW];
    uint8_t i;
    med_win[med_idx] = raw_mV;
    med_idx = (uint8_t)((med_idx + 1u) % TOWER_MED_WINDOW);
    if (med_len < TOWER_MED_WINDOW) {
        med_len++;
    }
    for (i = 0; i < TOWER_MED_WINDOW; i++) {
        win[i] = med_win[i];
    }
    return median_of(win, med_len);
}

/* ==================================================== rendering equation ==
 * rendering.equation: psi = (mV - 500) * 3 / 80
 * rendering.basis:    1/80 psi -- span 4000 mV * 3/80 = 150 psi
 *                     exactly; the calibration is exact integer arithmetic
 *                     by choice of unit (ST 1's basis trick).
 * Step 1 keeps 80ths of a psi -- psi80 = (mV - 500) * 3 -- and
 * never divides: the multiply is exact on the lattice.
 * rendering.range_psi: [0, 150] -- clamped here, before any
 * rounding, so the report never leaves the transducer's stated span.
 */
static int32_t render_psi80(int32_t mV)
{
    int32_t psi80 = (mV - TOWER_EQ_OFFSET_mV) * TOWER_EQ_NUM;
    if (psi80 < TOWER_PSI_MIN * TOWER_EQ_DEN) {
        psi80 = TOWER_PSI_MIN * TOWER_EQ_DEN;
    }
    if (psi80 > TOWER_PSI_MAX * TOWER_EQ_DEN) {
        psi80 = TOWER_PSI_MAX * TOWER_EQ_DEN;
    }
    return psi80;
}

/* Step 2 -- rendering.quantize: whole_psi. Pythagorean snapping, 1-D case
 * (ST 5.3): the report unit is chosen so the quantity sits ON the
 * lattice; quantizing to whole psi is round-to-nearest on it,
 * (psi80 + D/2)/D, exact integer arithmetic. psi80 >= 0 after the clamp,
 * so C truncation equals floor. No approximation anywhere: no floating
 * point because none is needed.
 */
static int32_t quantize_whole_psi(int32_t psi80)
{
    return (psi80 + TOWER_EQ_DEN / 2) / TOWER_EQ_DEN;
}

/* ==================================================== deadband judge ======
 * rendering.deadband: 1 whole psi -- dial deadband_psi (snap.dial)
 * FOUNDATION D2 with the integer metric and r = D, polarity inverted
 * (ST 5.2): WITHIN while d(psi, twin) <= D -- the deadband is a Schmitt
 * trigger against chatter -- SNAP when d > D. Judged in SQUARED form,
 * d*d > D*D: the comparison is monotone, needs no square root, and no
 * floating point. The weakest substrate sets the arithmetic (ST 5.3):
 * this exact integer comparison is what BOTH members of the snap pair
 * run, or the verdict itself could diverge across substrates.
 */
static int judge_snap(int32_t psi, int32_t twin, uint8_t twin_known)
{
    int32_t d;
    if (!twin_known) {
        return 1; /* first sighting: syncing the pair is a snap */
    }
    d = psi - twin;
    if (d < 0) {
        d = -d;
    }
    return d * d > (int32_t)TOWER_DEADBAND_WHOLE * TOWER_DEADBAND_WHOLE;
}

/* ========================================================= QUF state line =
 * The whole cell image as one line of key=value pairs -- the text form of
 * what a QUF container carries (all values integers; no floating point in
 * fleet state, QUF-SPEC 4). This is the maintenance surface (ST 6): the
 * entire rendering chain readable in one line, every stage auditable
 * against the equation quoted above. Keys are stable; consumers skip
 * unknown keys per QUF-SPEC 8. Integer formatting is hand-rolled: no
 * stdio, so the loop stays dependency-free and allocation-free.
 */
static char *quf_str(char *p, char *end, const char *s)
{
    while (p < end && *s != '\0') {
        *p++ = *s++;
    }
    return p;
}

static char *quf_u32(char *p, char *end, uint32_t v)
{
    char tmp[10];
    uint8_t i = 0;
    do {
        tmp[i++] = (char)('0' + (v % 10u));
        v /= 10u;
    } while (v != 0u);
    while (i != 0u && p < end) {
        *p++ = tmp[--i];
    }
    return p;
}

static char *quf_i32(char *p, char *end, int32_t v)
{
    char tmp[11];
    uint8_t i = 0;
    uint32_t u = (v < 0) ? (uint32_t)(-(int64_t)v) : (uint32_t)v;
    do {
        tmp[i++] = (char)('0' + (u % 10u));
        u /= 10u;
    } while (u != 0u);
    if (v < 0 && p < end) {
        *p++ = '-';
    }
    while (i != 0u && p < end) {
        *p++ = tmp[--i];
    }
    return p;
}

size_t tower_quf_line(char *buf, size_t n)
{
    char *p = buf;
    char *end = buf + n - 1u;
    p = quf_str(p, end, "QUF1 cell=" TOWER_CELL_NAME);
    p = quf_str(p, end, " tick=");       p = quf_u32(p, end, st_tick);
    p = quf_str(p, end, " raw_mV=");     p = quf_i32(p, end, st_raw_mV);
    p = quf_str(p, end, " med_mV=");     p = quf_i32(p, end, st_med_mV);
    p = quf_str(p, end, " psi80=");      p = quf_i32(p, end, st_psi80);
    p = quf_str(p, end, " psi=");        p = quf_i32(p, end, st_psi);
    p = quf_str(p, end, " twin=");       p = quf_i32(p, end, st_twin);
    p = quf_str(p, end, " " TOWER_DIAL_DEADBAND "=");
    p = quf_i32(p, end, TOWER_DEADBAND_WHOLE);
    p = quf_str(p, end, " posts=");      p = quf_u32(p, end, st_posts);
    p = quf_str(p, end, " snap_debt=");  p = quf_i32(p, end, st_snap_debt);
    if (p > end) {
        p = end;
    }
    *p = '\0';
    return (size_t)(p - buf);
}

/* ================================================================ qm_tick =
 * One fixed-timestep iteration of the whole chain (tick.period_ms =
 * 100 lives in the platform loop; the cell itself is cadence-agnostic
 * and deterministic per tick -- same delta-t every tick, game discipline
 * as cell anatomy, ST 5.4). Sense -> prefilter -> render -> quantize ->
 * judge -> snap. Nothing else happens, and nothing allocates.
 */
void tower_tick(void)
{
    st_tick++;
    st_raw_mV = tower_adc_read_mV();
    st_med_mV = prefilter_push(st_raw_mV);
    st_psi80 = render_psi80(st_med_mV);
    st_psi = quantize_whole_psi(st_psi80);
    if (judge_snap(st_psi, st_twin, st_twin_known)) {
        /* SNAP: reality wins (ST 5.1). Set the twin's belief to the
         * sensor value, book the drift as snap debt (the ST 5.4
         * account), and post the state line: the post IS the ledger
         * entry -- one line, both books. */
        int32_t d = st_twin_known ? (st_psi - st_twin) : 0;
        if (d < 0) {
            d = -d;
        }
        st_snap_debt += d;
        st_twin = st_psi;
        st_twin_known = 1;
        st_posts++;
        {
            char line[TOWER_QUF_LINE_MAX];
            (void)tower_quf_line(line, sizeof line);
            tower_twin_post(TOWER_TWIN_ENDPOINT, line);
        }
    }
}

/* ================================================================ reset ==
 * Zero the image (warm-start shape: what a QUF loader would restore).
 * The twin belief is forgotten, so the first tick after reset syncs it.
 */
void tower_reset(void)
{
    uint8_t i;
    for (i = 0; i < TOWER_MED_WINDOW; i++) {
        med_win[i] = 0;
    }
    med_len = 0;
    med_idx = 0;
    st_raw_mV = 0;
    st_med_mV = 0;
    st_psi80 = 0;
    st_psi = 0;
    st_twin = 0;
    st_twin_known = 0;
    st_posts = 0;
    st_snap_debt = 0;
    st_tick = 0;
}

/* ============================================================= accessors =
 * qm_view surface (FOUNDATION D4): bounded-freshness reads of the static
 * image; pure, always consistent, never torn.
 */
int32_t  tower_raw_mV(void)    { return st_raw_mV; }
int32_t  tower_med_mV(void)    { return st_med_mV; }
int32_t  tower_psi80(void)     { return st_psi80; }
int32_t  tower_psi_whole(void) { return st_psi; }
int32_t  tower_twin_psi(void)  { return st_twin; }
uint32_t tower_posts(void)     { return st_posts; }
int32_t  tower_snap_debt(void) { return st_snap_debt; }
uint32_t tower_ticks(void)     { return st_tick; }

/* Host/game-side seam: pretend the twin now holds v. The real pair learns
 * this from the game's own traffic; the verification harness uses it to
 * stage deadband tests. Not reachable from tower_tick -- belief moves
 * only on SNAP.
 */
void tower_twin_set_belief(int32_t v)
{
    st_twin = v;
    st_twin_known = 1;
}
