/* generated by qm2c.py from blink.qm + signals.json — do not edit */
#ifndef QM_PROG_H
#define QM_PROG_H

#define QM_ORGANISM "limb-blink"
#define QM_CANONICAL_SIGNAL 0

static const QmBind qm_binds[] = {
    { "limb-root", "{\"name\":\"limb-root\",\"role\":\"minimal spine — no rules, escalation target of record\",\"rule_count\":0,\"tier\":\"totipotent\"}" },
    { "limb-root:facts", "{\"name\":\"limb-root\",\"role\":\"minimal spine — no rules, escalation target of record\",\"rule_count\":0,\"tier\":\"totipotent\"}" },
    { "limb-root:response", NULL },
    { "led-limb", "{\"cost_per_call\":0,\"latency_ns\":0,\"name\":\"led-limb\",\"role\":\"blink limb — GPIO2 from rule table, zero model calls\",\"rule_count\":2,\"tier\":\"sclerotic\"}" },
    { "led-limb:facts", "{\"cost_per_call\":0,\"latency_ns\":0,\"name\":\"led-limb\",\"role\":\"blink limb — GPIO2 from rule table, zero model calls\",\"rule_count\":2,\"tier\":\"sclerotic\"}" },
    { "led-limb:response", NULL },
};
#define QM_N_BINDS 6

static const QmLink qm_links[] = {
    { "led-limb", "limb-root", "lineage" },
};
#define QM_N_LINKS 1

static const QmRule qm_rules[] = {
    { "led-limb:response", "tick", 1, (QmKv[]){ { "phase", "\"on\"" } },
      QM_SET, "{\"led\":true}", NULL, NULL },
    { "led-limb:response", "tick", 1, (QmKv[]){ { "phase", "\"off\"" } },
      QM_SET, "{\"led\":false}", NULL, NULL },
};
#define QM_N_RULES 2

static const QmViewDef qm_view_defs[] = {
    { "led-limb/facts", "led-limb:facts" },
    { "led-limb/response", "led-limb:response" },
    { "limb-root/response", "limb-root:response" },
};
#define QM_N_VIEWS 3

static const QmSignal qm_signals[] = {
    { "led-limb", "tick", 1, (QmKv[]){ { "phase", "\"on\"" } } },
    { "led-limb", "tick", 1, (QmKv[]){ { "phase", "\"off\"" } } },
    { "led-limb", "tick", 1, (QmKv[]){ { "phase", "\"sleep\"" } } },
    { "led-limb", "tick", 1, (QmKv[]){ { "phase", "\"on\"" } } },
    { "led-limb", "tick", 1, (QmKv[]){ { "phase", "\"off\"" } } },
};
#define QM_N_SIGNALS 5

#endif
