/* generated by qm_vessel2c.py from vessel-demo.qm — do not edit */
/* vessel-demo.qm rules v1 · exported 2026-08-27T02:30:00.000Z */
#ifndef VESSEL_QM_H
#define VESSEL_QM_H

#include <stdint.h>

#define VESSEL_QM_SHA256 "27a128bd61a10293d2dc3841f4c85afe5bb308dfb7e6f2916d4db158eecfb954"
#define VESSEL_QM_VERSION 1
#define VESSEL_QM_SCALE 1000000  /* 1 unit = 1e-6 — micro-units, same grid as reflex-arc */

/* frozen cell order (vessel-limb:facts.cells) — indexes match the
 * VESSEL_CELL_* defines the limb binds things under */
#define VESSEL_CELL_LAT 0
#define VESSEL_CELL_LON 1
#define VESSEL_CELL_FIX 2
#define VESSEL_CELL_HEADING 3
#define VESSEL_CELL_DEPTH 4
#define VESSEL_CELL_SOG 5
#define VESSEL_CELL_WSPEED 6
#define VESSEL_QM_N_CELLS 7

/* rule: geofence — Kodiak working box, µdeg */
typedef struct { int32_t lat_lo, lat_hi, lon_lo, lon_hi, margin; } vessel_box_t;
static const vessel_box_t VESSEL_QM_GEOFENCE = { 57750000, 57850000, -152500000, -152350000, 5000 };

/* rule: depth (DBT) — shallow alert, µm; 0 depth = no reading */
#define VESSEL_QM_DEPTH_WARN_BELOW  10000000
#define VESSEL_QM_DEPTH_ALERT_BELOW 5000000

/* rule: drift (anchored) — sog bands, µkn */
#define VESSEL_QM_DRIFT_WARN_ABOVE  500000
#define VESSEL_QM_DRIFT_ALERT_ABOVE 1000000

/* rule: nofix — severity when own.fix == 0 */
#define VESSEL_QM_NOFIX_SEV 1

#endif /* VESSEL_QM_H */
