/* generated by qm_gate2c.py from critic-gate.qm — do not edit */
/* gate-bands.json v3 · exported 2026-08-26T21:46:10.721Z */
#ifndef GATE_QM_H
#define GATE_QM_H

#include <stdint.h>

#define GATE_QM_SHA256 "9c896bb021e87b782c6a00121af830db9f86d9ded49ba6b3e6c35c4213a7e3e4"
#define GATE_QM_VERSION 3
#define GATE_QM_SCALE 1000000  /* 1 unit = 1e-6 — micro-units, not Q16.16 (see critic_gate.h) */
#define GATE_QM_AMBIGUITY 60000
#define GATE_QM_PENALTY_WARN 400000
#define GATE_QM_PENALTY_BAD 1000000
#define GATE_QM_REVISE_THRESHOLD 1000000
#define GATE_QM_DISSENT_EPS 20000
#define GATE_QM_N_CHANNELS 6

typedef struct { const char *name; int32_t lo; int32_t hi; } gate_band_t;

static const gate_band_t gate_qm_bands[GATE_QM_N_CHANNELS] = {
    { "note_density", 150000, 600000 },
    { "syncopation", 200000, 1000000 },
    { "register_spread", 50000, 250000 },
    { "rest_ratio", 0, 300000 },
    { "harmonic_tension", 150000, 763000 },
    { "interval_size", 0, 650000 },
};

#endif /* GATE_QM_H */
