/* generated by qm_eileen2c.py from eileen.qm — do not edit */
/* THE EILEEN, metal resolution · rules v1 · exported 2026-08-27T05:50:00.000Z */
/* materials: ai-writings/creative/the-eileen-a-vessel-built-of-days.md + ai-writings/creative/eileen.sheet.yaml + ai-writings/creative/the-eileen.mid + this */
#ifndef EILEEN_QM_H
#define EILEEN_QM_H

#include <stdint.h>

#define EILEEN_QM_SHA256 "8721b4bd042aa8c51006f1b2c9bd1eb9d36928a032b2e5e0bbf3ed9d5d4de36e"
#define EILEEN_QM_VERSION 1

/* frozen piece order (joint_order = the manifest's joint chain) */
#define EILEEN_CELL_KEEL 0
#define EILEEN_CELL_STEM 1
#define EILEEN_CELL_KEELSON 2
#define EILEEN_CELL_BREAST_HOOK 3
#define EILEEN_CELL_RIGGING 4
#define EILEEN_CELL_BULWARKS 5
#define EILEEN_CELL_ENSIGN 6
#define EILEEN_CELL_SCUPPERS 7
#define EILEEN_CELL_SHEERBOARD 8
#define EILEEN_CELL_FIGUREHEAD 9
#define EILEEN_QM_N_CELLS 10

/* the keel: value 1, the 2026-08-26 13:19 blink (blink.qm,
 * movement I of the bread score). ♩=60: 500 ms lit, 500 ms dark. */
#define EILEEN_KEEL_VALUE 1
#define EILEEN_KEEL_BLINK_MS 500

/* the joint chain, compile-time frozen — the manifest's order */
static const uint8_t EILEEN_QM_JOINTS[EILEEN_QM_N_CELLS] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, /* keel..figurehead */
};

/* the figurehead's closing line (log.figurehead) */
#define EILEEN_QM_LOG "she faces forward; the days grew from the keel"

/* integer discipline: day saturates so sheerboard=5N+3 fits int32 */
#define EILEEN_QM_DAY_MAX 429496728

#endif /* EILEEN_QM_H */
