#!/usr/bin/env python3
# Vendored from SuperInstance/cell-cascade, branch edge-benchmarks,
# tools/qm_compiler/benchmarks/qm2c.py — vendored 2026-08-26. Logic unaltered.
"""qm2c.py — compile a .qm program (+ signal fixture) into C static tables.

The edge-compiler step of the cell→qm bridge: the sclerotic rule table becomes
native data. All JSON values are canonicalized at COMPILE time (sorted keys,
UTF-8, no spaces — same algorithm as compile.ts canonJson / qm-runner canon),
so the C serve path is: route + strcmp guard match + effect/tick on the real
quilt-vm-c. No JSON parser on the target — that is the point.

Usage:
  qm2c.py <prog.qm> <signals.json> <canonical_signal_index> <out_header.h>
"""
import json
import sys


def canon(v) -> str:
    """Canonical JSON: sorted keys at every level, no spaces, UTF-8."""
    if isinstance(v, dict):
        body = ",".join(
            json.dumps(k, ensure_ascii=False) + ":" + canon(v[k])
            for k in sorted(v.keys())
        )
        return "{" + body + "}"
    if isinstance(v, list):
        return "[" + ",".join(canon(x) for x in v) + "]"
    return json.dumps(v, ensure_ascii=False)


def cstr(s: str) -> str:
    """Escape a python str into a C string literal (UTF-8 bytes pass through)."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\%03o" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    prog_path, sig_path, canon_idx, out_path = sys.argv[1:5]
    prog = json.load(open(prog_path, encoding="utf-8"))
    signals = json.load(open(sig_path, encoding="utf-8"))
    canon_idx = int(canon_idx)

    lines = []
    a = lines.append
    a(f"/* generated by qm2c.py from {prog_path} + {sig_path} — do not edit */")
    a("#ifndef QM_PROG_H")
    a("#define QM_PROG_H")
    a("")
    a(f'#define QM_ORGANISM {cstr(prog["organism"])}')
    a(f"#define QM_CANONICAL_SIGNAL {canon_idx}")
    a("")

    # ── BINDs ──
    binds = [(o["target"], o.get("value")) for o in prog["ops"] if o["op"] == "bind"]
    a(f"static const QmBind qm_binds[] = {{")
    for target, value in binds:
        if value is None:
            a(f"    {{ {cstr(target)}, NULL }},")
        else:
            a(f"    {{ {cstr(target)}, {cstr(canon(value))} }},")
    a("};")
    a(f"#define QM_N_BINDS {len(binds)}")
    a("")

    # ── LINKs ──
    links = [(o["from"], o["to"], o["type"]) for o in prog["ops"] if o["op"] == "link"]
    a("static const QmLink qm_links[] = {")
    for f, t, ty in links:
        a(f"    {{ {cstr(f)}, {cstr(t)}, {cstr(ty)} }},")
    a("};")
    a(f"#define QM_N_LINKS {len(links)}")
    a("")

    # ── EFFECTs (rule table) ──
    rules = [(o["target"], o["guard"], o["action"]) for o in prog["ops"] if o["op"] == "effect"]
    a("static const QmRule qm_rules[] = {")
    for target, guard, action in rules:
        kind = guard.get("kind")
        kind_c = cstr(kind) if kind is not None else "NULL"
        pe = guard.get("payload_equals") or {}
        if pe:
            pe_entries = ", ".join(
                "{ %s, %s }" % (cstr(k), cstr(canon(v))) for k, v in pe.items()
            )
            pe_init = f"(QmKv[]){{ {pe_entries} }}"
        else:
            pe_init = "NULL"
        a(f"    {{ {cstr(target)}, {kind_c}, {len(pe)}, {pe_init},")
        if "set" in action:
            a(f"      QM_SET, {cstr(canon(action['set']))}, NULL, NULL }},")
        else:
            e = action["expr"]
            a(f"      QM_EXPR, NULL, {cstr(e['centroid'])}, {cstr(e['sigma'])} }},")
    a("};")
    a(f"#define QM_N_RULES {len(rules)}")
    a("")

    # ── VIEWs ──
    views = prog.get("views") or []
    a("static const QmViewDef qm_view_defs[] = {")
    for v in views:
        a(f"    {{ {cstr(v['name'])}, {cstr(v['target'])} }},")
    a("};")
    a(f"#define QM_N_VIEWS {len(views)}")
    a("")

    # ── signals (the fixture, pre-canonicalized) ──
    a("static const QmSignal qm_signals[] = {")
    for s in signals:
        payload = s.get("payload") or {}
        if payload:
            entries = ", ".join(
                "{ %s, %s }" % (cstr(k), cstr(canon(v))) for k, v in payload.items()
            )
            pl_init = f"(QmKv[]){{ {entries} }}"
        else:
            pl_init = "NULL"
        a(f"    {{ {cstr(s['to'])}, {cstr(s['kind'])}, {len(payload)}, {pl_init} }},")
    a("};")
    a(f"#define QM_N_SIGNALS {len(signals)}")
    a("")
    a("#endif")
    open(out_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {out_path}: {len(binds)} binds, {len(links)} links, {len(rules)} rules, "
          f"{len(views)} views, {len(signals)} signals")


if __name__ == "__main__":
    main()
