#!/usr/bin/env python3
# quilt-esp32 — firmware/qm_gate2c.py
# Compile critic-gate.qm (the cell-cascade mint export, blink-style .qm)
# into gate_qm.h C tables. The .qm is the frozen DATA artifact; this step
# turns it into native integers for the fixed-point judge (critic_gate.c).
# Mirrors qm2c.py's doctrine: no JSON parser on the target — everything
# canonicalized/validated at compile time.
#
#   python3 qm_gate2c.py critic-gate.qm src/reflex/gate_qm.h
import json
import re
import sys

CANON_CHANNELS = [
    "note_density", "syncopation", "register_spread",
    "rest_ratio", "harmonic_tension", "interval_size",
]
SHA_RE = re.compile(r"^[0-9a-f]{64}$")


def die(msg: str) -> None:
    print(f"qm_gate2c: {msg}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    if len(sys.argv) != 3:
        die("usage: qm_gate2c.py <critic-gate.qm> <out gate_qm.h>")
    qm_path, out_path = sys.argv[1:5][:2]
    prog = json.load(open(qm_path, encoding="utf-8"))
    if prog.get("format") != "qm" or prog.get("version") != 1:
        die("not a .qm v1 program")
    if prog.get("organism") != "critic-gate":
        die(f"wrong organism: {prog.get('organism')}")

    facts = None
    for op in prog["ops"]:
        if op.get("op") == "bind" and op.get("target") == "critic-gate:facts":
            facts = op["value"]
    if facts is None:
        die("no critic-gate:facts bind")

    sha = facts.get("source_sha256", "")
    if not SHA_RE.match(sha):
        die(f"bad sha256 receipt: {sha!r}")
    fx = facts.get("fixed_point", {})
    scale = fx.get("scale")
    if scale != 1000000:
        die(f"unexpected scale {scale} — this compiler emits µ-units only")
    amb = fx.get("ambiguity_band")
    warn = fx.get("penalty", {}).get("warn")
    bad = fx.get("penalty", {}).get("bad")
    thr = fx.get("revise_threshold")
    eps = fx.get("dissent_epsilon")
    for name, v in (("ambiguity_band", amb), ("penalty.warn", warn),
                    ("penalty.bad", bad), ("revise_threshold", thr),
                    ("dissent_epsilon", eps)):
        if not isinstance(v, int) or isinstance(v, bool):
            die(f"fixed_point.{name} missing or not an integer: {v!r}")

    order = facts.get("channel_order", [])
    channels = facts.get("channels", [])
    if order != CANON_CHANNELS:
        die(f"channel_order must be the frozen CRITIC_FEATURES order, got {order}")
    if len(channels) != 6:
        die(f"expected 6 channels, got {len(channels)}")
    for c in channels:
        if c["name"] not in CANON_CHANNELS:
            die(f"unknown channel {c['name']}")
        if not (isinstance(c["lo"], int) and isinstance(c["hi"], int)):
            die(f"non-integer band for {c['name']}")
        if not (0 <= c["lo"] <= c["hi"] <= 1600000):
            die(f"band out of range for {c['name']}: [{c['lo']}, {c['hi']}]")

    L = []
    a = L.append
    a(f"/* generated by qm_gate2c.py from {qm_path} — do not edit */")
    a(f"/* gate-bands.json v{facts.get('gate_version')} · exported {facts.get('exported_at')} */")
    a("#ifndef GATE_QM_H")
    a("#define GATE_QM_H")
    a("")
    a("#include <stdint.h>")
    a("")
    a(f'#define GATE_QM_SHA256 "{sha}"')
    a(f"#define GATE_QM_VERSION {facts.get('gate_version')}")
    a("#define GATE_QM_SCALE 1000000  /* 1 unit = 1e-6 — micro-units, not Q16.16 (see critic_gate.h) */")
    a(f"#define GATE_QM_AMBIGUITY {amb}")
    a(f"#define GATE_QM_PENALTY_WARN {warn}")
    a(f"#define GATE_QM_PENALTY_BAD {bad}")
    a(f"#define GATE_QM_REVISE_THRESHOLD {thr}")
    a(f"#define GATE_QM_DISSENT_EPS {eps}")
    a("#define GATE_QM_N_CHANNELS 6")
    a("")
    a("typedef struct { const char *name; int32_t lo; int32_t hi; } gate_band_t;")
    a("")
    a("static const gate_band_t gate_qm_bands[GATE_QM_N_CHANNELS] = {")
    for c in channels:
        a(f'    {{ "{c["name"]}", {c["lo"]}, {c["hi"]} }},')
    a("};")
    a("")
    a("#endif /* GATE_QM_H */")
    open(out_path, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote {out_path}: v{facts.get('gate_version')} sha {sha[:16]}… "
          f"amb {amb}µ eps {eps}µ bands " +
          " ".join(f"{c['name']}[{c['lo']},{c['hi']}]" for c in channels))


if __name__ == "__main__":
    main()
