#!/usr/bin/env python3
# quilt-esp32 — firmware/qm_vessel2c.py
# Compile vessel-demo.qm (the vessel limb's rule sheet, critic-gate style)
# into vessel_qm.h C tables. The .qm is the source of truth — unlike
# critic-gate.qm (minted FROM gate-bands.json), this program is authored
# directly, so the mint receipt seals the file itself:
#
#   receipt = sha256( file bytes with the 64-hex source_sha256 value
#                     replaced by 64 '0' characters )
#
# `--mint` writes the receipt into the .qm in place (idempotent); compile
# mode verifies it. Mirrors qm2c.py/qm_gate2c.py doctrine: no JSON parser
# on the target — everything canonicalized/validated at compile time.
#
#   qm_vessel2c.py --mint vessel-demo.qm
#   qm_vessel2c.py vessel-demo.qm src/nmea/vessel_qm.h
import hashlib
import json
import re
import sys

CANON_CELLS = [
    "ais.position.lat", "ais.position.lon", "own.fix",
    "own.heading", "own.depth", "own.sog", "own.wspeed",
]
SHA_RE = re.compile(r"^[0-9a-f]{64}$")
ZERO = "0" * 64


def die(msg: str) -> None:
    print(f"qm_vessel2c: {msg}", file=sys.stderr)
    sys.exit(1)


def receipt_of(raw: bytes, receipt: str) -> str:
    """sha256 of the file bytes with the receipt value zeroed."""
    return hashlib.sha256(raw.replace(receipt.encode(), ZERO.encode())).hexdigest()


def load(qm_path: str):
    raw = open(qm_path, "rb").read()
    prog = json.loads(raw.decode("utf-8"))
    if prog.get("format") != "qm" or prog.get("version") != 1:
        die("not a .qm v1 program")
    if prog.get("organism") != "vessel-limb":
        die(f"wrong organism: {prog.get('organism')}")
    facts = None
    for op in prog["ops"]:
        if op.get("op") == "bind" and op.get("target") == "vessel-limb:facts":
            facts = op["value"]
    if facts is None:
        die("no vessel-limb:facts bind")
    return raw, facts


def mint(qm_path: str) -> None:
    raw, facts = load(qm_path)
    sha = facts.get("source_sha256", "")
    if not SHA_RE.match(sha):
        die(f"bad receipt field: {sha!r}")
    new = receipt_of(raw, sha)
    if sha == new:
        print(f"mint: receipt already sealed ({new[:16]}…)")
        return
    out = raw.replace(sha.encode(), new.encode())
    open(qm_path, "wb").write(out)
    print(f"mint: sealed receipt {new[:16]}… into {qm_path}")


def is_int(v) -> bool:
    return isinstance(v, int) and not isinstance(v, bool)


def main() -> None:
    if len(sys.argv) == 3 and sys.argv[1] == "--mint":
        mint(sys.argv[2])
        return
    if len(sys.argv) != 3:
        die("usage: qm_vessel2c.py <vessel-demo.qm> <out vessel_qm.h> | --mint <qm>")
    qm_path, out_path = sys.argv[1], sys.argv[2]
    raw, facts = load(qm_path)

    sha = facts.get("source_sha256", "")
    if not SHA_RE.match(sha):
        die(f"bad receipt field: {sha!r} (run --mint first)")
    if receipt_of(raw, sha) != sha:
        die("receipt does not verify: file changed since mint (re-run --mint to re-seal)")

    fx = facts.get("fixed_point", {})
    if fx.get("scale") != 1000000:
        die(f"unexpected scale {fx.get('scale')} — this compiler emits µ-units only")

    cells = [c["name"] for c in facts.get("cells", [])]
    if cells != CANON_CELLS:
        die(f"cell order must be the frozen order, got {cells}")

    rules = facts.get("rules", {})
    geo = rules.get("geofence", {})
    box = geo.get("box_udeg", {})
    for k in ("lat_lo", "lat_hi", "lon_lo", "lon_hi"):
        if not is_int(box.get(k)):
            die(f"geofence.box_udeg.{k} missing or not an integer")
    if not (-90000000 <= box["lat_lo"] < box["lat_hi"] <= 90000000):
        die(f"bad lat box: [{box['lat_lo']}, {box['lat_hi']}]")
    if not (-180000000 <= box["lon_lo"] < box["lon_hi"] <= 180000000):
        die(f"bad lon box: [{box['lon_lo']}, {box['lon_hi']}]")
    margin = geo.get("margin_udeg")
    if not (is_int(margin) and margin >= 0):
        die("geofence.margin_udeg missing or negative")

    dep = rules.get("depth", {})
    if not (is_int(dep.get("warn_below_um")) and is_int(dep.get("alert_below_um"))):
        die("depth thresholds missing")
    if not (0 < dep["alert_below_um"] < dep["warn_below_um"]):
        die(f"depth thresholds out of order: alert {dep['alert_below_um']} warn {dep['warn_below_um']}")

    drf = rules.get("drift", {})
    if not (is_int(drf.get("warn_above_ukn")) and is_int(drf.get("alert_above_ukn"))):
        die("drift thresholds missing")
    if not (0 < drf["warn_above_ukn"] < drf["alert_above_ukn"]):
        die(f"drift thresholds out of order: warn {drf['warn_above_ukn']} alert {drf['alert_above_ukn']}")

    nfx = rules.get("nofix", {})
    if not (is_int(nfx.get("severity")) and 0 <= nfx["severity"] <= 2):
        die("nofix.severity must be 0/1/2")

    L = []
    a = L.append
    a(f"/* generated by qm_vessel2c.py from {qm_path} — do not edit */")
    a(f"/* vessel-demo.qm rules v{facts.get('rule_version')} · exported {facts.get('exported_at')} */")
    a("#ifndef VESSEL_QM_H")
    a("#define VESSEL_QM_H")
    a("")
    a("#include <stdint.h>")
    a("")
    a(f'#define VESSEL_QM_SHA256 "{sha}"')
    a(f"#define VESSEL_QM_VERSION {facts.get('rule_version')}")
    a("#define VESSEL_QM_SCALE 1000000  /* 1 unit = 1e-6 — micro-units, same grid as reflex-arc */")
    a("")
    a("/* frozen cell order (vessel-limb:facts.cells) — indexes match the")
    a(" * VESSEL_CELL_* defines the limb binds things under */")
    for i, c in enumerate(CANON_CELLS):
        a(f"#define VESSEL_CELL_{['LAT','LON','FIX','HEADING','DEPTH','SOG','WSPEED'][i]} {i}")
    a(f"#define VESSEL_QM_N_CELLS {len(CANON_CELLS)}")
    a("")
    a("/* rule: geofence — Kodiak working box, µdeg */")
    a("typedef struct { int32_t lat_lo, lat_hi, lon_lo, lon_hi, margin; } vessel_box_t;")
    a(f"static const vessel_box_t VESSEL_QM_GEOFENCE = {{ {box['lat_lo']}, {box['lat_hi']}, {box['lon_lo']}, {box['lon_hi']}, {margin} }};")
    a("")
    a("/* rule: depth (DBT) — shallow alert, µm; 0 depth = no reading */")
    a(f"#define VESSEL_QM_DEPTH_WARN_BELOW  {dep['warn_below_um']}")
    a(f"#define VESSEL_QM_DEPTH_ALERT_BELOW {dep['alert_below_um']}")
    a("")
    a("/* rule: drift (anchored) — sog bands, µkn */")
    a(f"#define VESSEL_QM_DRIFT_WARN_ABOVE  {drf['warn_above_ukn']}")
    a(f"#define VESSEL_QM_DRIFT_ALERT_ABOVE {drf['alert_above_ukn']}")
    a("")
    a("/* rule: nofix — severity when own.fix == 0 */")
    a(f"#define VESSEL_QM_NOFIX_SEV {nfx['severity']}")
    a("")
    a("#endif /* VESSEL_QM_H */")
    open(out_path, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote {out_path}: rules v{facts.get('rule_version')} sha {sha[:16]}… "
          f"geofence lat[{box['lat_lo']},{box['lat_hi']}] lon[{box['lon_lo']},{box['lon_hi']}] +{margin}µ "
          f"depth alert<{dep['alert_below_um']}/warn<{dep['warn_below_um']} "
          f"drift warn>{drf['warn_above_ukn']}/alert>{drf['alert_above_ukn']}")


if __name__ == "__main__":
    main()
